// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MacOSApp_Game_2
{
	public partial class Room_123_ViewController : NSViewController
	{
		public Room_123_ViewController(IntPtr handle) : base(handle)
		{
		}
	}
}
