// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using AppKit;

namespace MacOSApp_Game_2
{
	public partial class Room121ViewController : NSViewController
	{
		string _currentText;
		int _charIndex;

		public Room121ViewController(IntPtr handle) : base(handle)
		{
		}
		
		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			// Make the corners rounded
			dialog_121.WantsLayer = true;
			if (dialog_121.Layer != null)
			{
				dialog_121.Layer.CornerRadius = 10f;

				var textColor = NSColor.White;
				dialog_121.TextColor = textColor;

				// Change the text field color
				var textFieldColor =
					NSColor.FromRgba(0x52 / 255f, 0x42 / 255f, 0x5C / 255f, 1f);
				dialog_121.BackgroundColor = textFieldColor;
				//52425C
				//675373

				// Update the text field appearance
				dialog_121.Layer.BackgroundColor = textFieldColor.CGColor;
				dialog_121.Layer.BorderColor = textFieldColor.CGColor;
				dialog_121.Layer.BorderWidth = 1f;
			}

			// Set the font size to 14sp
			var fontSize = 14f;
			var font = NSFont.SystemFontOfSize(fontSize, NSFontWeight.Regular);
			dialog_121.Font = font;
			
			/* // Add padding to the text field
			var paddedText = new NSMutableAttributedString(dialog_121.StringValue);
			var range = new NSRange(0, paddedText.Length);
			paddedText.AddAttribute(NSStringAttributeKey.ParagraphStyle, new NSMutableParagraphStyle { HeadIndent = 10f }, range);
			dialog_121.Cell.AttributedStringValue = paddedText; */
		}

		private readonly string[] _array121 =
		{
			"Чудово! Твоя мета – створити програму, яка обчислює суму двох цілих чисел. Код написаний мовою " +
			"програмування Python і складається із трьох блоків. Тобі потрібно обрати та розставити блоки в " +
			"правильній послідовності.", "Не хвилюйся, якщо чогось не розумієш. Я залишив для тебе підказки. " + 
			"Щоб їх подивитись, натисни на знак питання поряд із завданням. " +
			"Готовий? Тоді натискай на екран ноутбука, що стоїть на столі. Ти впораєшся!"
		};
		
		private int _click;
		
		partial void submit_dialog (NSButton sender)
		{
			if (_click < 2)
			{
				dialog_121.StringValue = "";
				_currentText = _array121[_click];
				_charIndex = 0;
				NSTimer.CreateRepeatingScheduledTimer(TimeSpan.FromMilliseconds(20), TimerAction);
				//dialog_121.StringValue = array_121[i];
				_click++;
			}
			if (_click >= 2)
			{
				sender.Enabled = false; // Disables the button
			}
		}
		void TimerAction(NSTimer timer)
		{
			if (_charIndex < _currentText.Length)
			{
				InvokeOnMainThread(() => {
					dialog_121.StringValue += _currentText[_charIndex];
				});
				_charIndex++;
			}
			else
			{
				timer.Invalidate();
			}
		}
	}
}
