// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Threading.Tasks;
using CoreGraphics;
using Foundation;
using AppKit;

namespace MacOSApp_Game_2
{
	public static class Result122
	{
		public static string ResultPercent = "-";
	}
	public partial class Task_122_ViewController : NSViewController
	{
		private NSImage _rightAnswerImage;
		private NSImage _wrongAnswerImage;
		string _currentText;
		int _charIndex;
		
		public Task_122_ViewController(IntPtr handle) : base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			NSColor backgroundColor = NSColor.FromRgb(
				(nfloat) (0xDF / 255.0),
				(nfloat) (0xE4 / 255.0),
				(nfloat) (0xEA / 255.0)
			);

			// Set the background color of the view
			View.WantsLayer = true;
			if (View.Layer != null) View.Layer.BackgroundColor = backgroundColor.CGColor;
			
			// Make the corners rounded
			task_text_122.WantsLayer = true;
			if (task_text_122.Layer != null)
			{
				task_text_122.Layer.CornerRadius = 10f;

				var textColor = NSColor.White;
				task_text_122.TextColor = textColor;

				// Change the text field color
				var textFieldColor =
					NSColor.FromRgba(0xF8 / 255f, 0x8B / 255f, 0xCD / 255f, 1f);
				task_text_122.BackgroundColor = textFieldColor;
				// ED96CB
				// f88bcd

				// Update the text field appearance
				task_text_122.Layer.BackgroundColor = textFieldColor.CGColor;
				task_text_122.Layer.BorderColor = textFieldColor.CGColor;
				task_text_122.Layer.BorderWidth = 1f;
			}

			// Set the font size to 14sp
			var fontSize = 14f;
			var font = NSFont.SystemFontOfSize(fontSize, NSFontWeight.Regular);
			task_text_122.Font = font;
			
			
			// Завантаження зображень
			var rightAnswerImagePath = "/Users/milana/Desktop/uni/knu/coursework/MacOSApp_Game_2/MacOSApp_Game_2/Resources/right_answer.png";
			var wrongAnswerImagePath = "/Users/milana/Desktop/uni/knu/coursework/MacOSApp_Game_2/MacOSApp_Game_2/Resources/wrong_answer.png";
			_rightAnswerImage = new NSImage(rightAnswerImagePath);
			_wrongAnswerImage = new NSImage(wrongAnswerImagePath);
		}
		private readonly string[] _array121 =
		{
			"Для зручності можеш записувати свої нотатки в текстове поле поряд із завданням. Воно ніяк не вплине на " +
			"оцінювання, а лише допоможе тобі не заплутатись у сортуванні."
		};
		//Для зручності можеш записувати свої замітки в текстове поле під завданням. Воно ніяк не вплине на оцінювання, 
		private int _click;
		
		partial void submit_dialog122 (NSButton sender)
		{
			if (_click < 1)
			{
				task_text_122.StringValue = "";
				_currentText = _array121[_click];
				_charIndex = 0;
				NSTimer.CreateRepeatingScheduledTimer(TimeSpan.FromMilliseconds(20), TimerAction);
				//dialog_121.StringValue = array_121[i];
				_click++;
			}
			if (_click >= 1)
			{
				sender.Enabled = false; // Disables the button
			}
		}
		void TimerAction(NSTimer timer)
		{
			if (_charIndex < _currentText.Length)
			{
				InvokeOnMainThread(() => {
					task_text_122.StringValue += _currentText[_charIndex];
				});
				_charIndex++;
			}
			else
			{
				timer.Invalidate();
			}
		}
		
		private void DisplayImageForCombo(NSComboBox comboBox, string correctItem, CGPoint position)
		{
			var selectedItem = comboBox.StringValue;
			var imageView = new NSImageView(new CGRect(position.X, position.Y, 30, 30));

			if (selectedItem == correctItem)
			{
				imageView.Image = _rightAnswerImage;
			}
			else
			{
				imageView.Image = _wrongAnswerImage;
			}

			View.AddSubview(imageView);
		}

		partial void check_button_task122(NSButton sender)
		{
			// Disable the button
			sender.Enabled = false;
	
			// Disable combo boxes
			task122_ComboBox_11.Enabled = false;
			task122_ComboBox_12.Enabled = false;
			task122_ComboBox_13.Enabled = false;
			task122_ComboBox_21.Enabled = false;
			task122_ComboBox_22.Enabled = false;
			task122_ComboBox_31.Enabled = false;

			// Display images for selected items
			DisplayImageForCombo(task122_ComboBox_11, "3 7 9 2 42 23", new CGPoint(218, 398));
			DisplayImageForCombo(task122_ComboBox_12, "3 7 2 9 42 23", new CGPoint(473, 398));
			DisplayImageForCombo(task122_ComboBox_13, "3 7 2 9 23 42", new CGPoint(738, 398));
			DisplayImageForCombo(task122_ComboBox_21, "3 2 7 9 23 42", new CGPoint(218, 295));
			DisplayImageForCombo(task122_ComboBox_22, "не потрібен", new CGPoint(473, 295));
			DisplayImageForCombo(task122_ComboBox_31, "2 3 7 9 23 42", new CGPoint(274, 213));

			// Count the number of correct answers
			int correctAnswersCount = 0;


			// Check selected items and increment the count
			if (task122_ComboBox_11.StringValue == "3 7 9 2 42 23")
				correctAnswersCount++;

			if (task122_ComboBox_12.StringValue == "3 7 2 9 42 23")
				correctAnswersCount++;

			if (task122_ComboBox_13.StringValue == "3 7 2 9 23 42")
				correctAnswersCount++;
			
			if (task122_ComboBox_21.StringValue == "3 2 7 9 23 42")
				correctAnswersCount++;

			if (task122_ComboBox_22.StringValue == "не потрібен")
				correctAnswersCount++;

			if (task122_ComboBox_31.StringValue == "2 3 7 9 23 42")
				correctAnswersCount++;

			// Display the result gradually
			DisplayResultText(correctAnswersCount);
		}
		
		private async void DisplayResultText(int correctAnswersCount)
		{
			string resultText;

			if (correctAnswersCount == 0)
			{
				// Clear the existing text
				task_text_122.StringValue = "";
				resultText = "О ні! У тебе жодної правильної відповіді, але не хвилюйся! Ти зможеш розібратися з " +
				             "усім в університеті. Тебе там усього навчать! А поки що можеш спробувати свої сили в інших " +
				             "спеціальностях.";
				Result122.ResultPercent = "0";
				//Console.WriteLine(Result121.ResultPercent);
			}
			else if (correctAnswersCount == 1)
			{
				// Clear the existing text
				task_text_122.StringValue = "";
				resultText = "Твій результат 16.7%. Сподіваюсь, тебе зацікавило це завдання. Якщо так, " +
				             "то я чекаю тебе на спеціальності комп'ютерні науки. А поки що можеш " +
				             "спробувати свої сили в інших спеціальностях.";
				Result122.ResultPercent = "16.7";
				//Console.WriteLine(Result121.ResultPercent);
			}
			else if (correctAnswersCount == 2)
			{
				// Clear the existing text
				task_text_122.StringValue = "";
				resultText = "Твій результат 33.3%. Непогано! Сподіваюсь, тобі сподобалось працювати з алгоритмами " +
				             "сортування. Якщо так, то комп'ютерні науки саме для тебе! А поки що можеш спробувати свої " +
				             "сили в інших спеціальностях.";
				Result122.ResultPercent = "33.3";
				//Console.WriteLine(Result121.ResultPercent);
			}
			else if (correctAnswersCount == 3)
			{
				// Clear the existing text
				task_text_122.StringValue = "";
				resultText = "Твій результат 50%. Досить непогано! Сподіваюсь, тебе зацікавило це завдання. " +
				             "Якщо так, то комп'ютерні науки саме для тебе! А поки що можеш спробувати свої сили в " +
				             "інших спеціальностях.";
				Result122.ResultPercent = "50";
				//Console.WriteLine(Result121.ResultPercent);
			}
			else if (correctAnswersCount == 4)
			{
				// Clear the existing text
				task_text_122.StringValue = "";
				resultText = "Твій результат 66.7%. Чудово! Сподіваюсь, тобі сподобалось працювати з алгоритмами " +
				             "сортування. Якщо так, то комп'ютерні науки саме для тебе! А поки що можеш спробувати свої " +
				             "сили в інших спеціальностях.";
				Result122.ResultPercent = "66.7";
				//Console.WriteLine(Result121.ResultPercent);
			}
			else if (correctAnswersCount == 5)
			{
				// Clear the existing text
				task_text_122.StringValue = "";
				resultText = "Твій результат 83.3%. Чудово! Сподіваюсь, тобі сподобалось працювати з алгоритмами " +
				             "сортування. Якщо так, то комп'ютерні науки саме для тебе! А поки що можеш спробувати свої " +
				             "сили в інших спеціальностях.";
				Result122.ResultPercent = "83.3";
				//Console.WriteLine(Result121.ResultPercent);
			}
			else if (correctAnswersCount == 6)
			{
				// Clear the existing text
				task_text_122.StringValue = "";
				resultText = "Твій результат приголомшливий! 100% правильних відповідей! Сподіваюсь, тобі сподобалось " +
				             "працювати з алгоритмами сортування. Якщо так, то комп'ютерні науки саме для тебе! А " +
				             "поки що можеш спробувати свої сили в інших спеціальностях.";
				Result122.ResultPercent = "100";
				//Console.WriteLine(Result121.ResultPercent);
			}
			else
			{
				return; // Invalid count
			}

			// Clear the existing text
			task_text_122.StringValue = "";

			// Display the text gradually
			foreach (char c in resultText)
			{
				task_text_122.StringValue += c;
				await Task.Delay(TimeSpan.FromMilliseconds(20));
			}
		}
	}
}
